[package]
name = "async-cffi-codegen"
version = "0.1.0"
edition = "2024"

[lib]
name = "async_cffi_codegen"
crate-type = ["rlib"]

[dependencies]
async-cffi = "0.1.0"
rs-schema = "1.0.0"
handlebars = "6.3.2"
serde_json = "1.0.145"
heck = "0.5"
anyhow = "1.0"
